# Generated by Django 5.2 on 2025-04-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muallif',
            name='jins',
            field=models.CharField(choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol')], max_length=20),
        ),
    ]
