# Generated by Django 5.2 on 2025-04-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_muallif_jins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='qaytargan_sana',
            field=models.DateField(blank=True, null=True),
        ),
    ]
